version: '3.4'

services:
  db:
    image: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  omero:
    build:
      context: ..
      target: run
      args:
        - BUILD_IMAGE
    environment:
      - ROOTPASS=${ROOTPASS}
      - CONFIG_omero_db_user=postgres
      - CONFIG_omero_db_name=postgres
      - CONFIG_omero_db_pass=${POSTGRES_PASSWORD}
      - CONFIG_omero_upgrades_url=
      - CONFIG_Ice_IPv6=0
      - PYTHONPATH=/opt/omero/server/OMERO.server/lib/python
    ports:
      - "${OMERO_SERVER_TCP}4063"
      - "${OMERO_SERVER_SSL}4064"
  test:
    build:
      context: ..
      target: build
      args:
        - BUILD_IMAGE
    stdin_open: true
    tty: true
